'use strict';
const $=id=>document.getElementById(id);
let csrf='',me=null,view='overview',generation=0,authEpoch=0,actionBusy=false,saving=false,commerceEnabled=false,mfaPending=false,mfaEnabled=false,currentAnnouncement='';
const filters={},titles={overview:'总览',users:'用户管理',nodes:'节点管理',plans:'套餐',orders:'订单',audit:'操作审计',settings:'设置与公告'};
const descriptions={overview:'每一处连接与授权，都清晰可见。',users:'查看账号状态，管理授权、额度与访问权限。',nodes:'在一个地方，管理所有节点与接入配置。',plans:'为不同的使用需求，安排合适的额度与周期。',orders:'查看订单记录，核实开通与处理待办。',audit:'每一次管理操作，都有迹可循。',settings:'调整注册、试用、公告与客户端更新信息。'};
const element=(tag,value,cls)=>{const e=document.createElement(tag);if(value!==undefined)e.textContent=value;if(cls)e.className=cls;return e;};
function icon(name){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg'),use=document.createElementNS('http://www.w3.org/2000/svg','use');svg.setAttribute('class','icon');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('aria-hidden','true');svg.setAttribute('focusable','false');use.setAttribute('href','./icons.svg#'+name);svg.append(use);return svg;}
function badge(label,tone='neutral',name){const e=element('span',undefined,'pill '+tone);if(name)e.append(icon(name));e.append(element('span',label));return e;}
function cell(value,code=false){const e=element('span',value,'cell-main'+(code?' cell-code':''));e.title=String(value);return e;}
function auditIdentity(name,value){const result=element('div');result.append(cell(name||value||'—'));if(name&&value&&name!==value)result.append(element('small',value,'cell-code'));return result;}
function auditOperation(entry){const labels={register:'注册账号',login:'登录',logout:'退出登录',node_saved:'保存节点',node_deleted:'删除节点',node_status:'调整节点状态',node_scope_changed:'调整节点范围',plan_saved:'保存套餐',plan_deleted:'删除套餐',order_created:'创建订单',order_cancelled:'取消订单',order_fulfilled:'核实并开通订单',payment_paid:'确认付款',payment_refunded:'确认退款',external_refund_confirmed:'登记外部退款',payment_settings_saved:'保存支付配置',settings_saved:'保存网站设置',role_changed:'调整用户分组',role_migrated:'旧分组迁移为用户',user_status:'调整账户状态',user_deleted:'删除账号',password_reset:'管理员重置密码',password_changed:'修改本人密码',user_token_rotated:'重设凭证',mfa_enabled:'开启二次验证',mfa_disabled:'关闭二次验证',security_verify:'验证邮箱',security_reset:'通过邮件重置密码',ticket_created:'创建工单',ticket_reply:'回复工单',ticket_close:'关闭工单',incident_opened:'产生告警',incident_resolved:'告警恢复',incident_ack:'确认告警',beta_invite_created:'生成邀请',trial:'激活试用',user_renewed:'手工续期'},result=element('div');result.append(cell(entry.summary||labels[entry.action]||entry.action));result.append(element('small',entry.action,'cell-code'));return result;}
function auditChanges(entry){const changes=Array.isArray(entry.changes)?entry.changes:[];if(!changes.length)return element('span',entry.summary?'无字段变更':'历史记录未保存字段差异','muted');const details=element('details',undefined,'audit-changes');details.append(element('summary','查看 '+changes.length+' 项变更'));details.append(table(['字段','变更前','变更后'],changes.map(change=>[change.label||change.field,cell(change.before===''?'（空）':change.before??'—'),cell(change.after===''?'（空）':change.after??'—')])));return details;}
function nodeProbeStatus(node){const result=element('span',undefined,'node-probe-status');if(!node.last_probe){result.append(badge('尚未探测','neutral'));return result;}const at=new Date(node.last_probe*1000).toLocaleTimeString('zh-CN',{timeZone:'Asia/Shanghai',hour:'2-digit',minute:'2-digit'});result.append(badge(node.probe_ok?'探测成功':'探测失败',node.probe_ok?'good':'bad'),element('small',at+' · '+Number(node.probe_latency_ms||0)+' ms'));result.title=(node.probe_ok?'外部探测成功':'外部探测失败')+' · '+date(node.last_probe)+' · 连接检查耗时 '+Number(node.probe_latency_ms||0)+' ms';return result;}
function buttonIcon(label){if(label.includes('下载'))return'download';if(label.includes('添加')||label.includes('新增'))return'plus';if(label.includes('编辑'))return'edit';if(label.includes('删除'))return'trash';if(label.includes('解除'))return'shield';if(label.includes('封禁'))return'lock';if(label.includes('停用'))return'pause';if(label.includes('启用'))return'play';if(label.includes('密码')||label.includes('凭据')||label.includes('凭证'))return'key';if(label.includes('续期'))return'clock';if(label.includes('取消'))return'close';if(label.includes('订单'))return'orders';if(label.includes('开通')||label.includes('试用'))return'check';return'arrow';}
const message=e=>{$('message').textContent=e instanceof Error?e.message:String(e||'');};
const bytes=n=>{n=n||0;const u=['B','KiB','MiB','GiB','TiB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++;}return n.toFixed(i?1:0)+' '+u[i];};
const date=n=>n?new Date(n*1000).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'}):'—';
const id=value=>encodeURIComponent(value);
function accountState(u){if(u.disabled)return'已封禁';if(u.verification_required)return'待验证邮箱';if(u.traffic_exhausted)return'流量耗尽';if(u.subscription_status==='valid')return'订阅有效';if(u.subscription_status==='scheduled')return'待生效';if(u.subscription_status==='expired')return'已到期';return u.active?'已开通':'未开通';}
function accountTraffic(u){return u.traffic||{total_bytes:u.traffic_limit||0,used_bytes:(u.upload||0)+(u.download||0),remaining_bytes:Math.max(0,(u.traffic_limit||0)-(u.upload||0)-(u.download||0)),unlimited:!u.traffic_limit&&!!u.active};}
const gigabytes=n=>(Math.max(0,Number(n)||0)/1073741824).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})+' GiB';
function trafficCell(u){const q=accountTraffic(u),box=element('span',undefined,'user-traffic'),total=q.unlimited?'不限':gigabytes(q.total_bytes);if(!q.unlimited){const p=element('progress');p.max=Math.max(1,q.total_bytes);p.value=Math.min(q.used_bytes,q.total_bytes);p.setAttribute('aria-label',u.email+' 当前周期流量用量');box.append(p);}box.append(element('span',gigabytes(q.used_bytes)+' / '+total),element('small',q.test?'测试':'正式'));box.title='总量 '+total+' · 已用 '+gigabytes(q.used_bytes)+' · 剩余 '+(q.unlimited?'不限':gigabytes(q.remaining_bytes))+' · '+(q.test?'测试节点':'正式节点')+' · '+(q.current_period?'当前有效周期':'账号额度');return box;}
async function createUser(){const plans=commerceEnabled?(await admin('plans')).filter(p=>p.enabled&&p.kind!=='traffic'):[];const planOptions=[['','不分配套餐'],...plans.map(p=>[p.id,p.name+' · '+p.days+' 天 · '+(p.traffic_bytes?gigabytes(p.traffic_bytes):'不限流量')])];modal('新增用户',[{name:'email',label:'邮箱',type:'email'},{name:'password',label:'密码（12 至 256 字节）',type:'password',minlength:12,maxlength:256,autocomplete:'new-password'},...(commerceEnabled?[{name:'plan_id',label:'分配套餐（可选）',type:'select',value:'',options:planOptions,required:false}]:[])],d=>admin('users',{email:d.email,password:d.password,plan_id:d.plan_id||''}));$('dialog-description').textContent=commerceEnabled?'管理员直接创建账号，跳过注册与邮箱验证。如选择套餐，账号创建后立即生效（正式节点）。':'管理员直接创建账号，跳过注册与邮箱验证。创建后可在列表中使用「续期」开通授权。';}
async function assignUserPlan(u){const plans=(await admin('plans')).filter(p=>p.enabled);if(!plans.length)throw Error('请先添加并启用套餐。');const requestID=Array.from(crypto.getRandomValues(new Uint8Array(16)),v=>v.toString(16).padStart(2,'0')).join('');modal('分配套餐 · '+u.email,[{name:'plan_id',label:'套餐',type:'select',value:plans[0].id,options:plans.map(p=>[p.id,p.name+' · '+(p.kind==='traffic'?'流量包':p.days+' 天')+' · '+(p.traffic_bytes?gigabytes(p.traffic_bytes):'不限流量')])},{name:'mode',label:'生效方式（流量包始终立即加入当前周期）',type:'select',value:'immediate',options:[['immediate','立即生效：保留已有权益，叠加额度'],['renew','到期续订：当前周期结束后生效']]},{name:'scope',label:'适用节点范围',type:'select',value:u.traffic?.test?'test':'live',options:u.beta?[['test','测试节点'],['live','正式节点']]:[['live','正式节点']]},{name:'reason',label:'分配原因（保留在权益和审计中）',type:'textarea',minlength:4,maxlength:1000}],d=>admin('users/'+id(u.id)+'/assign-plan',{plan_id:d.plan_id,mode:d.mode,test:d.scope==='test',reason:d.reason,request_id:requestID}));$('dialog-description').textContent='管理员直接授予套餐权益，不产生付款订单。原有套餐和已用流量保留；到期时间与流量额度分别计算。';}
function busy(){document.querySelectorAll('[data-action]').forEach(b=>b.disabled=actionBusy||saving);}
function resetAuth(reason){authEpoch++;generation++;me=null;csrf='';view='overview';mfaPending=false;mfaEnabled=false;updateSecurityGate();document.body.dataset.mode='guest';delete document.body.dataset.role;delete $('content').dataset.page;$('login').hidden=false;$('content').hidden=true;$('content').replaceChildren();$('logout').hidden=true;$('identity').hidden=true;$('identity').replaceChildren();$('nav').replaceChildren();$('title').textContent='欢迎回来';$('network-state').textContent='安全连接，清晰管理';if($('dialog').open)$('dialog').close();message(reason);publicSettings();if(typeof publicShop==='function')publicShop();}
async function api(path,body,binary=false){
 const epoch=authEpoch,controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000),mutating=body!==undefined;
 try{
  const r=await fetch(new URL('api/'+path,location.href),{method:mutating?'POST':'GET',credentials:'same-origin',cache:'no-store',signal:controller.signal,headers:mutating?{'Content-Type':'application/json','X-CSRF-Token':csrf}:{},body:mutating?JSON.stringify(body):undefined});
  if(r.ok&&binary)return await r.blob();
  let data;try{data=await r.json();}catch{throw Error('服务器返回了无效响应，请稍后刷新重试。');}
  if(!r.ok){if(data.mfa_required&&path==='login')$('otp-wrap').hidden=false;if(r.status===401&&epoch===authEpoch&&path!=='login'&&path!=='register')resetAuth(me?'登录已失效，请重新登录。':'');const error=Error(data.error||'请求失败（HTTP '+r.status+'）');error.mfa_required=r.status===403&&!!data.mfa_required;if(error.mfa_required&&me){mfaPending=true;mfaEnabled=!!data.mfa_enabled;updateSecurityGate();}throw error;}
  return data;
 }catch(e){if(e.name==='AbortError')throw Error(mutating?'请求超时，操作结果尚未确认，请刷新核实后再试。':'请求超时，请稍后重试。');if(e instanceof TypeError)throw Error('无法连接管理服务，请检查网络后重试。');throw e;}finally{clearTimeout(timer);}
}
const admin=(path,body)=>api('admin/'+path,body);
async function action(fn){if(actionBusy||saving)return;actionBusy=true;busy();message('');try{await fn();}catch(e){if(e.mfa_required&&me){view='security';try{await refreshIdentity();}catch{}}message(e);}finally{actionBusy=false;busy();}}
const button=(label,fn,cls,name)=>{const b=element('button',undefined,cls);b.append(icon(name||buttonIcon(label)),element('span',label));b.type='button';b.dataset.action='';b.disabled=actionBusy||saving;b.onclick=()=>action(fn);return b;};
function actions(...items){const e=element('div',undefined,'actions');e.append(...items);return e;}
// Fixed slots keep every row's buttons in the same columns; null leaves an empty slot.
function slotActions(columns,...slots){const e=element('div',undefined,'actions slot-actions');e.style.gridTemplateColumns=columns;e.append(...slots.map(b=>b||element('span',undefined,'action-slot')));return e;}
function card(root,title,description,name){const c=element('section',undefined,'card');if(title){const head=element('div',undefined,'card-head'),copy=element('div'),heading=element('div',undefined,'card-heading');if(name)heading.append(icon(name));heading.append(element('h2',title));copy.append(heading);if(description)copy.append(element('p',description,'card-description'));head.append(copy);c.append(head);}root.append(c);return c;}
function section(root,title,description,total,name,add){const c=card(root,title,description,name),tools=actions(element('span',total+' 条记录','record-count'));if(add)tools.append(add);c.querySelector('.card-head').append(tools);return c;}
function table(headers,rows){const wrap=element('div',undefined,'table-wrap'),t=element('table'),head=element('tr'),thead=element('thead'),body=element('tbody');headers.forEach(h=>{const th=element('th',h);th.scope='col';head.append(th);});thead.append(head);t.append(thead,body);for(const row of rows){const tr=element('tr');for(const value of row){const td=element('td');if(value instanceof Node)td.append(value);else td.textContent=String(value??'');tr.append(td);}body.append(tr);}wrap.append(t);if(!rows.length){const empty=element('div',undefined,'empty'),art=element('span',undefined,'empty-art');art.append(icon('empty'));empty.append(art,element('strong','暂无记录'),element('small','新的记录会显示在这里。'));wrap.append(empty);}return wrap;}
function listing(headers,records,row,key){
 const root=element('div',undefined,'list-panel'),search=element('input'),searchWrap=element('div',undefined,'list-search'),result=element('div'),controls=element('div',undefined,'pagination');
 search.type='search';search.placeholder='搜索名称、邮箱或 ID';search.setAttribute('aria-label','搜索记录');search.value=filters[key]||'';let page=0;const size=20;
 function draw(){const query=search.value.trim().toLowerCase(),data=records.filter(r=>JSON.stringify(r).toLowerCase().includes(query)),pages=Math.max(1,Math.ceil(data.length/size));page=Math.min(page,pages-1);result.replaceChildren(table(headers,data.slice(page*size,(page+1)*size).map(row)));const prev=element('button'),next=element('button'),buttons=element('div',undefined,'page-buttons');prev.append(icon('left'),element('span','上一页'));next.append(element('span','下一页'),icon('right'));prev.type=next.type='button';prev.disabled=page===0;next.disabled=page===pages-1;prev.onclick=()=>{page--;draw();};next.onclick=()=>{page++;draw();};buttons.append(prev,next);controls.replaceChildren(element('span','第 '+(page+1)+' / '+pages+' 页 · 共 '+data.length+' 条记录'),buttons);}
 search.oninput=()=>{filters[key]=search.value;page=0;draw();};searchWrap.append(icon('search'),search);root.append(searchWrap,result,controls);draw();return root;
}
function download(name,data){const blob=data instanceof Blob?data:new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type:'application/octet-stream'}),url=URL.createObjectURL(blob),a=element('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function number(value,min,max,integer=true){const n=Number(value);if(String(value).trim()===''||!Number.isFinite(n)||n<min||n>max||(integer&&!Number.isInteger(n)))throw Error('数字超出允许范围，请检查表单。');return n;}
function modal(title,fields,save){
 if(saving)return;$('save').hidden=false;$('save').querySelector('span').textContent='保存';$('cancel').textContent='取消';$('dialog-title').textContent=title;$('fields').replaceChildren();$('dialog-error').textContent='';
 $('dialog-icon').querySelector('use').setAttribute('href','./icons.svg#'+buttonIcon(title));$('dialog-description').textContent=title.includes('节点')&&!title.includes('删除')?'节点参数需与服务器一致，修改后在客户端下次连接时生效。':title.includes('删除')?'请输入完整名称确认。历史订单、计数与审计记录将继续保留。':'检查填写内容后保存，设置将更新到管理中心。';
 for(const field of fields){const label=element('label',field.label),tag=field.type==='textarea'?'textarea':field.type==='select'?'select':'input',input=element(tag);input.name=field.name;
  // textarea.type and select.type are read-only DOM properties.
  if(tag==='input')input.type=field.type||'text';input.required=field.required!==false;
  if(field.type==='select')for(const[value,title]of field.options){const option=element('option',title);option.value=value;input.append(option);}
  input.value=field.value??'';for(const attr of ['min','max','step','minlength','maxlength','autocomplete'])if(field[attr]!==undefined)input.setAttribute(attr,field[attr]);if(tag==='textarea'||fields.length<=2||['server_name','sha256','url','password'].includes(field.name))label.classList.add('field-wide');label.append(input);$('fields').append(label);
 }
 $('edit-form').onsubmit=async e=>{e.preventDefault();if(saving||actionBusy||!e.target.reportValidity())return;saving=true;busy();$('save').disabled=$('cancel').disabled=true;$('dialog-error').textContent='';
  let continuation;
  try{const next=await save(Object.fromEntries(new FormData(e.target)));if($('dialog').open)$('dialog').close();if(me){message('已保存。');await render();if(typeof next==='function')continuation=next;}}
  catch(error){if($('dialog').open)$('dialog-error').textContent=error.message||String(error);else message(error);}
  finally{saving=false;busy();$('save').disabled=$('cancel').disabled=false;}
  if(continuation)continuation();
 };$('dialog').showModal();
}
$('cancel').onclick=()=>{if(!saving)$('dialog').close();};$('dialog').addEventListener('cancel',e=>{if(saving)e.preventDefault();});
function entitlementFields(u){return[{name:'days',label:'增加天数',type:'number',value:30,min:1,max:3650,step:1},{name:'gib',label:'增加额度 GiB（0 表示不限）',type:'number',value:100,min:0,max:1048576,step:'any'},{name:'devices',label:'同一节点同时使用设备数',type:'number',value:u.device_limit||3,min:1,max:32,step:1},{name:'speed',label:'限速 Mbps（0 表示不限速）',type:'number',value:(u.speed_limit||0)/125000,min:0,max:8589,step:'any'}];}
function entitlement(d){return{days:number(d.days,1,3650),traffic_bytes:Math.round(number(d.gib,0,1048576,false)*1073741824),devices:number(d.devices,1,32),speed_limit:Math.round(number(d.speed,0,8589,false)*125000)};}
async function planEditor(p){const nodes=await admin('nodes');const selected=new Set(p?.node_ids||[]);for(const node of selected)if(!nodes.some(n=>n.id===node))nodes.push({id:node,name:'已删除节点 · '+node});modal(p?'编辑套餐':'新增套餐',[
 {name:'name',label:'名称',value:p?.name||'',maxlength:128},{name:'days',label:'有效天数',type:'number',value:p?.days||30,min:1,max:3650,step:1},
 {name:'price',label:'金额（按所选币种）',type:'number',value:p?(p.price_cents/100).toFixed(2):0,min:0,max:10000000,step:0.01},
 {name:'gib',label:'流量 GiB（0 表示不限）',type:'number',value:p?p.traffic_bytes/1073741824:100,min:0,max:1048576,step:'any'},
 {name:'devices',label:commerceEnabled?'跨节点同时使用设备数':'同一节点同时使用设备数',type:'number',value:p?.devices||3,min:1,max:32,step:1},
 {name:'speed',label:'限速 Mbps（0 表示不限速，使用全局默认）',type:'number',value:p?p.speed_limit/125000:0,min:0,max:8589,step:'any'},
 {name:'kind',label:'套餐类型',type:'select',value:p?.kind||'subscription',options:[['subscription','周期套餐'],['traffic','当前周期流量加购']]},
 {name:'currency',label:'币种',type:'select',value:p?.currency||'cny',options:[['cny','人民币 CNY'],['usd','美元 USD'],['eur','欧元 EUR']]},
 {name:'enabled',label:'状态',type:'select',value:String(p?.enabled??true),options:[['true','启用'],['false','停用']]},
 {name:'node_scope',label:'可使用节点',type:'select',value:selected.size?'selected':'all',options:[['all','全部节点'],['selected','仅选定节点']]}
],d=>{const ids=d.node_scope==='selected'?nodes.filter(n=>d['plan_node_'+n.id]==='true').map(n=>n.id):[];if(d.node_scope==='selected'&&!ids.length)throw Error('请至少选择一个节点，或明确改为全部节点。');return admin(p?'plans/'+id(p.id):'plans',{name:d.name.trim(),...entitlement(d),price_cents:Math.round(number(d.price,0,10000000,false)*100),enabled:d.enabled==='true',kind:d.kind,currency:d.currency,node_ids:ids});});const group=element('fieldset',undefined,'node-scope-choices field-wide');group.append(element('legend','选择此套餐可使用的节点'));for(const node of nodes){const label=element('label',undefined,'node-scope-choice'),input=element('input');input.type='checkbox';input.name='plan_node_'+node.id;input.value='true';input.checked=selected.has(node.id);label.append(input,element('span',node.name+(node.test_only?' · 测试节点':'')));group.append(label);}if(!nodes.length)group.append(helpNote('先添加节点，再设置指定节点套餐。'));const scope=$('fields').querySelector('[name=node_scope]');scope.onchange=()=>{group.hidden=scope.value!=='selected';};scope.onchange();$('fields').append(group,helpNote('流量加购沿用当前有效套餐的到期时间和设备限制，不延长使用周期。节点调整只影响之后创建的订单。'));}
function removeUser(u){modal('删除账号 · '+u.email,[{name:'email',label:'输入完整邮箱确认删除：'+u.email,type:'email'}],d=>{if(d.email.trim().toLowerCase()!==u.email)throw Error('邮箱不一致。');return admin('users/'+id(u.id)+'/delete',{email:d.email}).then(()=>()=>message('已删除账号 '+u.email+'。'));});$('dialog-description').textContent='删除后该账号无法登录，节点连接会在几秒内断开，未付款订单、权益、工单与登录会话一并清除，此操作不可撤销。有付款记录的账号不能删除，请改用封禁；审计记录会保留。';}
function deleteRecord(kind,r){modal('删除已停用'+(kind==='nodes'?'节点':'套餐'),[{name:'name',label:'输入名称确认删除：'+r.name}],d=>{if(d.name!==r.name)throw Error('名称不一致。');return admin(kind+'/'+id(r.id)+'/delete',d);});}
function installCommand(data){
 $('dialog-title').textContent='在节点服务器执行';$('dialog-description').textContent='使用 root 登录 Ubuntu / Debian，复制并执行下方命令。有效期至 '+date(data.expires_at)+'，安装完成后后台自动显示状态。';$('dialog-icon').querySelector('use').setAttribute('href','./icons.svg#key');$('dialog-error').textContent='';$('fields').replaceChildren();$('save').hidden=true;$('cancel').textContent='关闭';$('edit-form').onsubmit=e=>e.preventDefault();
 const label=element('label','一键安装命令','field-wide'),input=element('textarea',undefined,'install-command');input.value=data.command;input.readOnly=true;input.rows=7;input.setAttribute('aria-label','一键安装命令');label.append(input);
 const copy=button('复制命令',async()=>{try{await navigator.clipboard.writeText(data.command);$('dialog-error').textContent='已复制。';}catch{input.focus();input.select();$('dialog-error').textContent='已选中命令，请按 Ctrl+C 复制。';}},'primary','key');
 $('fields').append(label,actions(copy),helpNote(data.certificate_mode==='private'?'自建证书模式：无需域名解析或开放 80/443，只需放行节点 TCP 端口。证书自动续期，私钥留在节点。安装命令包含限时凭据，请只在对应服务器执行。':'安装命令包含限时凭据，请只在对应服务器执行。域名需直接指向节点 IP；云安全组需开放 80、443 和节点 TCP 端口。'));$('dialog').showModal();
}
const scopeOptions=[['false','正式节点'],['true','测试节点']];
// The clipboard write starts inside the click so the user gesture is still valid once the command arrives.
async function copyInstallCommand(n){const pending=admin('nodes/'+id(n.id)+'/install',{});let early=null;try{if(window.ClipboardItem&&navigator.clipboard?.write)early=navigator.clipboard.write([new ClipboardItem({'text/plain':pending.then(d=>new Blob([d.command],{type:'text/plain'}))})]);}catch{}early?.catch(()=>{});const data=await pending;let copied=false;try{if(!early)throw Error();await early;copied=true;}catch{try{await navigator.clipboard.writeText(data.command);copied=true;}catch{}}await render();if(copied)message('「'+n.name+'」的一键安装命令已复制，有效至 '+date(data.expires_at)+'。请用 root 在节点服务器执行；之前生成的命令已失效。');else installCommand(data);}
function nodeScope(n){modal('调整节点范围 · '+n.name,[{name:'test_only',label:'节点范围',type:'select',value:String(!!n.test_only),options:scopeOptions}],d=>admin('nodes/'+id(n.id)+'/scope',{test_only:d.test_only==='true'}));$('dialog-description').textContent='测试节点只接受模拟付款开通的测试权益，正式节点只接受正式权益。仍被套餐、待付订单或有效权益指定，或仍有使用中的流量预留时不能调整；调整后该节点上的连接会按新范围重新认证。';}
async function nodeSetup(){const testMode=commerceEnabled&&(await api('public/commerce')).test_mode;modal('添加节点并生成命令',[
 {name:'name',label:'节点名称',maxlength:128},{name:'region',label:'地区（选填）',value:'HK',required:false,maxlength:32},
 {name:'ip',label:'服务器公网 IP'},{name:'port',label:'节点 TCP 端口',type:'number',value:8443,min:1024,max:65535,step:1},
 {name:'certificate_mode',label:'证书方式',type:'select',value:'public',options:[['public','公开证书 · 已有域名'],['private','自建证书 · 无需购买域名']]},
 {name:'domain',label:'已指向此 IP 的域名',maxlength:253},
 {name:'inner_name',label:'内层证书名称（选填，留空自动生成）',required:false,maxlength:253},
 ...(commerceEnabled?[{name:'test_only',label:'节点范围'+(testMode?'（模拟付款模式默认测试节点）':''),type:'select',value:String(!!testMode),options:scopeOptions}]:[])
],async d=>{const data=await admin('nodes/setup',{name:d.name.trim(),region:d.region.trim(),ip:d.ip.trim(),port:number(d.port,1024,65535),domain:d.domain.trim(),certificate_mode:d.certificate_mode,inner_name:d.inner_name.trim(),test_only:d.test_only==='true'});return()=>installCommand(data);});$('dialog-description').textContent='填写连接信息，生成 Ubuntu / Debian 一键安装命令。';
 const mode=$('fields').querySelector('[name=certificate_mode]'),domain=$('fields').querySelector('[name=domain]'),note=helpNote('');$('fields').append(note);
 mode.onchange=()=>{const privateCA=mode.value==='private';domain.required=!privateCA;domain.placeholder=privateCA?'例如 gateway.tunnelx.invalid；留空自动生成':'例如 node.example.com';domain.parentElement.firstChild.textContent=privateCA?'外层证书名称（选填，无需注册或解析）':'已指向此 IP 的域名';note.textContent=privateCA?'通过 IP 连接，客户端自动校验证书。内外层名称均可自定义，外层名称在握手中可见。只需开放节点 TCP 端口。':'域名需直接解析到此服务器，并开放 80/443 和节点端口。内层名称用于加密握手中的证书校验，可留空自动生成。';};mode.onchange();}
async function nodeEditor(n){const value=n?await admin('nodes/'+id(n.id)):null,testMode=!n&&commerceEnabled&&(await api('public/commerce')).test_mode;modal(n?'编辑 H2 节点':'添加 H2 节点',[
 {name:'name',label:'名称',value:value?.name||'',maxlength:128},{name:'region',label:'地区',value:value?.region||'HK',maxlength:32},
 {name:'server_name',label:'TLS 内层名称（严格 ECH）',value:value?.client.server_name||'edge.tunnelx.invalid'},
 {name:'server_ip',label:'固定引导 IP',value:value?.client.server_ip||''},{name:'port',label:'TCP 端口',type:'number',value:value?.client.port||8443,min:1,max:65535,step:1},
 {name:'ech_config',label:'ECHConfigList（Base64）',type:'textarea',value:value?.client.ech_config||''},{name:'ca_pem',label:'origin CA PEM（仅证书）',type:'textarea',value:value?.ca_pem||''},
 {name:'enabled',label:'状态',type:'select',value:String(value?.enabled??true),options:[['true','启用'],['false','停用']]},
 ...(!n&&commerceEnabled?[{name:'test_only',label:'节点范围'+(testMode?'（模拟付款模式默认测试节点）':''),type:'select',value:String(!!testMode),options:scopeOptions}]:[])
],d=>admin(n?'nodes/'+id(n.id):'nodes',{name:d.name.trim(),region:d.region.trim(),enabled:d.enabled==='true',test_only:n?!!value.test_only:d.test_only==='true',ca_pem:d.ca_pem,client:{...(value?.client||{}),server_name:d.server_name.trim(),server_ip:d.server_ip.trim(),port:number(d.port,1,65535),ech_config:d.ech_config.trim()}}));if(n&&commerceEnabled)$('fields').append(helpNote('此节点为'+(value.test_only?'测试节点':'正式节点')+'。如需切换，请在节点列表中使用「调整范围」。'));}
function updateSecurityGate(){const gate=$('mfa-gate');if(!gate)return;gate.hidden=!mfaPending;$('mfa-gate-description').textContent=mfaEnabled?'此会话尚未通过二次验证，请使用验证码或恢复码重新登录。':'请在账号安全中绑定验证器，完成后会自动解锁管理页面。';$('mfa-gate-link').textContent=mfaEnabled?'去完成二次验证':'去开启二次验证';}
async function openSecurity(){view='security';history.replaceState(null,'',location.pathname+location.search+'#security');if(me)await render();else message('请先登录，登录后会直接进入账号安全。');}
for(const key of ['mfa-gate-link','security-entry'])if($(key))$(key).onclick=e=>{e.preventDefault();return action(openSecurity);};
window.addEventListener('hashchange',()=>{if(location.hash==='#security')openSecurity().catch(message);});
async function refreshIdentity(){
 const epoch=authEpoch,d=await api('me');if(epoch!==authEpoch)return;me=d.user;csrf=d.csrf;currentAnnouncement=d.announcement||'';document.body.dataset.mode='member';document.body.dataset.role=me.role;const copy=element('div',undefined,'identity-copy');copy.append(element('strong',me.email),element('small',me.role==='admin'?'管理员工作空间':'个人工作空间'));$('identity').replaceChildren(element('span',me.email[0].toUpperCase(),'avatar'),copy);$('identity').title=me.email;$('identity').hidden=false;$('login').hidden=true;$('content').hidden=false;$('logout').hidden=false;
 const entries=me.role==='admin'?[['overview','总览'],['users','用户'],['nodes','节点'],['plans','套餐'],['orders','订单'],['audit','审计'],['settings','设置与公告']]:[['overview','我的账号'],['nodes','可用节点'],['plans','套餐'],['orders','我的订单']];
 commerceEnabled=!!d.commerce;$('public-shop').hidden=true;entries.push(['security','账号安全'],['support','售后工单']);if(commerceEnabled){entries.push(['billing','我的账单']);if(me.role==='admin')entries.push(['payments','付款与退款']);if(me.role==='admin')entries.push(['paymentconfig','支付配置']);if(me.role==='admin')entries.push(['operations','运维告警']);}
 mfaPending=!!d.security?.admin_mfa_required&&!d.security?.mfa_session&&me.role==='admin';mfaEnabled=!!d.security?.mfa_enabled;updateSecurityGate();if(mfaPending)view='security';else if(entries.some(([key])=>location.hash==='#'+key))view=location.hash.slice(1);if(!entries.some(([key])=>key===view))view=entries[0][0];$('nav').replaceChildren(...entries.map(([key,title])=>{const b=button(title,async()=>{view=key;await render();},undefined,({security:'shield',support:'mail',billing:'orders',payments:'orders',paymentconfig:'orders',operations:'network'})[key]||key);b.dataset.view=key;b.append(element('span',undefined,'nav-dot'));return b;}));await render();
}
async function authenticate(register){if(!$('auth-form').reportValidity())return;await api(register?'register':'login',{email:$('email').value,password:$('password').value,code:$('otp').value,invite:$('invite').value});authEpoch++;$('password').value='';$('otp').value='';await refreshIdentity();}
$('auth-form').onsubmit=e=>{e.preventDefault();return action(()=>authenticate(false));};$('register').onclick=()=>action(()=>authenticate(true));
$('logout').onclick=()=>action(async()=>{await api('logout',{});resetAuth('已退出登录。');});
function helpNote(text){const p=element('p',undefined,'help-note');p.append(icon('info'),element('span',text));return p;}
function clientDownload(root,release){if(!release?.url)return;let url;try{url=new URL(release.url);}catch{return;}if(url.protocol!=='https:'||url.username||url.password)return;const link=element('a','下载 Windows 客户端 '+release.version,'client-download');link.href=url.href;link.target='_blank';link.rel='noopener noreferrer';root.append(link);if(release.sha256)root.append(helpNote('文件 SHA256：'+release.sha256));}
function hasUnreadAnnouncement(){try{return!!currentAnnouncement&&currentAnnouncement!==(localStorage.getItem('tx_ann')||'');}catch{return false;}}
function markAnnouncementRead(){try{localStorage.setItem('tx_ann',currentAnnouncement);}catch{}}
function trafficChart(history){
 if(!history||history.length<2)return helpNote('流量趋势需要至少两个小时的运行数据，请稍后查看。');
 const deltas=[];for(let i=1;i<history.length;i++){const up=Math.max(0,history[i].upload-history[i-1].upload),down=Math.max(0,history[i].download-history[i-1].download);deltas.push({time:history[i].time,up,down,total:up+down});}
 const recent=deltas.slice(-48);if(!recent.length)return helpNote('暂无流量变化记录。');
 const W=560,H=150,pt=14,pr=10,pb=26,pl=50,ns='http://www.w3.org/2000/svg',cw=W-pl-pr,ch=H-pt-pb,maxVal=Math.max(1,...recent.map(d=>d.total)),barW=Math.max(3,(cw/recent.length)-2);
 const svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 '+W+' '+H);svg.setAttribute('class','traffic-chart');svg.setAttribute('aria-label','流量时序图表');
 for(let i=0;i<=3;i++){const y=pt+(i/3)*ch,line=document.createElementNS(ns,'line');line.setAttribute('x1',pl);line.setAttribute('x2',W-pr);line.setAttribute('y1',y);line.setAttribute('y2',y);line.setAttribute('stroke','#e8e3d9');svg.append(line);const t=document.createElementNS(ns,'text');t.setAttribute('x',pl-6);t.setAttribute('y',y+3);t.setAttribute('text-anchor','end');t.setAttribute('class','chart-label');t.textContent=bytes(maxVal*(1-i/3));svg.append(t);}
 const fmt=new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'numeric',day:'numeric',hour:'2-digit',hourCycle:'h23'});
 recent.forEach((d,i)=>{const x=pl+i*(barW+2),totalH=(d.total/maxVal)*ch;if(d.up>0){const r=document.createElementNS(ns,'rect');r.setAttribute('x',x);r.setAttribute('y',pt+ch-totalH);r.setAttribute('width',barW);r.setAttribute('height',(d.up/maxVal)*ch);r.setAttribute('fill','var(--sage)');r.setAttribute('rx','1.5');svg.append(r);}if(d.down>0){const r=document.createElementNS(ns,'rect');r.setAttribute('x',x);r.setAttribute('y',pt+ch-(d.down/maxVal)*ch);r.setAttribute('width',barW);r.setAttribute('height',(d.down/maxVal)*ch);r.setAttribute('fill','var(--accent)');r.setAttribute('rx','1.5');svg.append(r);}
  if(i===0||i===recent.length-1||recent.length<=12||i%Math.ceil(recent.length/6)===0){const t=document.createElementNS(ns,'text');t.setAttribute('x',x+barW/2);t.setAttribute('y',H-4);t.setAttribute('text-anchor','middle');t.setAttribute('class','chart-label');t.textContent=fmt.format(new Date(d.time*1000));svg.append(t);}
 });
 const legend=element('div',undefined,'chart-legend');legend.append(element('span','','chart-dot upload'),document.createTextNode(' 上传  '),element('span','','chart-dot download'),document.createTextNode(' 下载'));
 const wrap=element('div');wrap.append(svg,legend);return wrap;
}
function nodeTrafficBars(nodes){
 if(!nodes||!nodes.length)return helpNote('暂无节点流量数据。');
 const sorted=nodes.slice().sort((a,b)=>((b.upload||0)+(b.download||0))-((a.upload||0)+(a.download||0)));
 const maxT=Math.max(1,...sorted.map(n=>(n.upload||0)+(n.download||0)));
 const list=element('div',undefined,'node-bars');let any=false;
 for(const n of sorted){const total=(n.upload||0)+(n.download||0);if(!total)continue;any=true;const row=element('div',undefined,'node-bar-row'),name=element('span',n.name,'node-bar-name'),bar=element('div',undefined,'node-bar-track'),fill=element('div',undefined,'node-bar-fill');fill.style.width=(total/maxT*100)+'%';bar.append(fill);const val=element('span',bytes(total),'node-bar-value');row.append(name,bar,val);list.append(row);}
 return any?list:helpNote('各节点尚无流量记录。');
}
function overview(root,profile,summary,isAdmin){
 const hour=Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Shanghai',hour:'2-digit',hourCycle:'h23'}).format(new Date())),greeting=hour<6?'夜深了':hour<12?'上午好':hour<18?'下午好':'晚上好';
 const welcome=element('section',undefined,'welcome-card'),copy=element('div',undefined,'welcome-copy'),kicker=element('p',undefined,'section-kicker');kicker.append(element('span'),document.createTextNode('你的工作空间，一目了然'));
 copy.append(kicker,element('h2',greeting+'，'+(isAdmin?'管理员':me.email.split('@')[0])+'。'),element('p',isAdmin?'节点状态、账号授权与日常管理，都在这里。':'查看你的账号授权，选择节点，开始连接。'),actions(button('查看节点',async()=>{view='nodes';await render();},'primary','nodes'),button('查看订单',async()=>{view='orders';await render();},undefined,'orders')));
 const art=element('img',undefined,'welcome-art');art.src='./network.svg';art.alt='';art.setAttribute('aria-hidden','true');art.width=255;art.height=175;welcome.append(copy,art);root.append(welcome);
 if(!isAdmin){const usage=accountTraffic(me),metrics=element('div',undefined,'member-metrics');metrics.setAttribute('aria-label','当前周期流量');for(const[label,value,name]of [['套餐总量',usage.unlimited?'不限流量':bytes(usage.total_bytes),'plans'],['本期已用',bytes(usage.used_bytes),'download'],['剩余流量',usage.unlimited?'不限流量':bytes(usage.remaining_bytes),'shield']]){const tile=element('section',undefined,'card member-metric'),mark=element('span',undefined,'member-metric-icon');mark.append(icon(name));tile.append(mark,element('small',label),element('strong',value));metrics.append(tile);}root.append(metrics);}

 if(summary){const grid=element('div',undefined,'metrics');for(const[key,label,name,note]of [['users','用户总数','users','当前已注册的账号'],['nodes','已登记节点','nodes','工作空间中的全部节点'],['online_nodes','在线节点','network','最近 90 秒内收到心跳'],['orders','订单记录','orders','已创建的全部订单']]){const c=element('section',undefined,'card metric'),top=element('div',undefined,'metric-top'),mark=element('span',undefined,'metric-icon');mark.append(icon(name));top.append(element('small',label),mark);c.append(top,element('b',summary[key]),element('div',note,'metric-note'));grid.append(c);}root.append(grid);$('network-state').textContent=summary.online_nodes+' / '+summary.nodes+' 节点在线';}
 const grid=element('div',undefined,'dashboard-grid');root.append(grid);const account=card(grid,'我的账号','当前账号的授权与用量','user'),heading=element('div',undefined,'account-heading'),name=element('div',undefined,'account-name'),avatar=element('span',undefined,'avatar'),info=element('div');avatar.append(icon('user'));info.append(element('strong',me.email),element('small',isAdmin?'管理员账号':'个人账号'));name.append(avatar,info);const state=me.active?'可使用':accountState(me);heading.append(name,badge(state,me.active?'good':me.disabled?'bad':'warm',me.active?'check':me.disabled?'lock':'clock'));account.append(heading);
 const stats=element('div',undefined,'account-stats'),expiry=me.expires_at?new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(me.expires_at*1000)):'未开通';
 for(const[label,value,name]of [['到期时间',expiry,'clock'],['累计上传',bytes(me.upload),'upload'],['累计下载',bytes(me.download),'download']]){const stat=element('div',undefined,'account-stat'),labelNode=element('small');labelNode.append(icon(name),document.createTextNode(label));stat.append(labelNode,element('strong',value));stats.append(stat);}account.append(stats);
 const traffic=accountTraffic(me),used=traffic.used_bytes,quota=element('div',undefined,'quota-summary');quota.append(element('span','流量额度'),element('span',bytes(used)+' / '+(traffic.unlimited?'不限流量':bytes(traffic.total_bytes))));account.append(quota);
 if(!traffic.unlimited){const progress=element('progress');progress.max=Math.max(1,traffic.total_bytes);progress.value=Math.min(used,traffic.total_bytes);progress.setAttribute('aria-label','已使用流量');account.append(progress);}else account.append(element('p','本账号没有流量额度上限。','unlimited-note'));account.append(element('p','剩余流量：'+(traffic.unlimited?'不限':bytes(traffic.remaining_bytes)),'muted'));
 const foot=element('div',undefined,'account-footer');foot.append(icon('shield'),document.createTextNode(profile.commerce?'设备限制：'+me.device_limit+' 台；计费节点跨节点共享。':'每个节点最多同时使用 '+me.device_limit+' 台设备'));account.append(foot);
 if(!profile.commerce&&!me.trial_used&&!me.active&&!isAdmin&&profile.trial_hours)account.append(button('激活 '+profile.trial_hours+' 小时试用（1 GiB）',async()=>{await api('trial',{});await render();},'primary'));
 const quick=card(grid,'快捷入口','让常用操作，少一步距离。','spark'),links=isAdmin?[['users','用户与授权','查看账号状态，调整访问权限'],['nodes','节点与接入','查看节点状态，管理接入配置'],['orders','订单记录','核实开通，查看订单进度']]:[['nodes','可用节点','下载接入配置，选择你的连接'],['plans','套餐与额度','查看适合自己的使用方案'],['orders','我的订单','查看订单与开通状态']];
 for(const[key,title,description]of links){const b=button('',async()=>{view=key;await render();},'quick-link',key),text=element('span');b.replaceChildren(icon(key));text.append(element('strong',title),element('small',description));b.append(text,icon('right'));quick.append(b);}
 if(isAdmin&&summary){const tc=card(root,'流量趋势','近期总流量的每小时变化与各节点流量分布。','download');tc.append(trafficChart(summary.traffic_history));const sub=element('div',undefined,'traffic-subsection');sub.append(element('h3','节点流量分布'));sub.append(nodeTrafficBars(summary.node_traffic));tc.append(sub);}
 const bottom=element('div',undefined,'overview-bottom');root.append(bottom);card(bottom,'工作空间公告','最近的消息与使用提醒','info').append(element('p',profile.announcement||'新的工作空间公告会显示在这里。'));markAnnouncementRead();
 const start=card(bottom,'开始使用','选择适合你的连接方式','network');start.append(element('p','在桌面客户端登录并选择节点，或从「可用节点」下载配置 ZIP。连接后，即可通过本地代理访问网络。'));clientDownload(start,profile.release);
}
async function render(){
 if(!me)return;if(mfaPending)view='security';const current=view,ticket=++generation,epoch=authEpoch,isAdmin=me.role==='admin',root=element('div');let profile,data,users,summary;
 if(current==='overview')[profile,summary]=await Promise.all([api('me'),isAdmin?admin('summary'):Promise.resolve(null)]);
 if(current==='users')data=await admin('users');if(current==='nodes')data=await api(isAdmin?'admin/nodes':'nodes');if(current==='plans')data=await api(isAdmin?'admin/plans':'plans');
 if(current==='orders')[data,users]=await Promise.all([api(isAdmin?'admin/orders':'orders'),isAdmin?admin('users'):Promise.resolve([])]);
 if(current==='audit')data=await admin('audit');if(current==='settings')data=await admin('settings');
 if(['security','support','billing','payments','paymentconfig','operations'].includes(current))await commerceView(root,current);
 if(ticket!==generation||epoch!==authEpoch||!me)return;
 if(['users','nodes','plans','orders','audit'].includes(current))data=data||[];
 if(current==='overview'){me=profile.user;currentAnnouncement=profile.announcement||'';overview(root,profile,summary,isAdmin);}
 if(current==='users')section(root,'账户与授权','在这里查看账号状态，管理每一份访问权限。',data.length,'users',button('新增用户',()=>createUser(),'primary')).append(listing(['邮箱','分组','状态','到期','流量用量','操作'],data,u=>[
  cell(u.email),badge(({admin:'管理员',user:'用户'})[u.role]||u.role,u.role==='admin'?'accent':'neutral'),badge(accountState(u),u.disabled?'bad':u.active?'good':'warm',u.disabled?'lock':u.active?'check':'clock'),date(u.expires_at),trafficCell(u),
  slotActions('repeat('+(commerceEnabled?5:4)+',76px) 56px',
   u.role==='admin'?null:button(u.disabled?'解除封禁':'封禁',async()=>{await admin('users/'+id(u.id)+'/update',{disabled:!u.disabled});await render();}),
   u.role==='admin'?null:commerceEnabled?button('分配套餐',()=>assignUserPlan(u)):button('续期',()=>modal('续期 · '+u.email,entitlementFields(u),d=>admin('users/'+id(u.id)+'/renew',entitlement(d)))),
   ...(commerceEnabled?[u.id!==me.id?button('管理分组',()=>modal('管理分组 · '+u.email,[{name:'role',label:'分组（修改后需要重新登录）',type:'select',value:u.role,options:[['admin','管理员'],['user','用户']]}],d=>admin('users/'+id(u.id)+'/role',d))):null]:[]),
   button('重置密码',()=>modal('重置密码 · '+u.email,[{name:'password',label:'新密码（12 至 256 字节）',type:'password',minlength:12,maxlength:256,autocomplete:'new-password'}],async d=>{await admin('users/'+id(u.id)+'/password',d);if(u.id===me?.id)resetAuth('密码已更新，请使用新密码重新登录。');})),
   button('重设凭证',async()=>{await admin('users/'+id(u.id)+'/rotate',{});message('凭据已更换，客户端需重新连接。');}),
   u.role==='admin'?null:button('删除',()=>removeUser(u),'danger'))
 ],current));
 if(current==='nodes'){
  const c=section(root,isAdmin?'节点工作空间':'可用节点','查看接入状态，找到需要的节点与配置。',data.length,'nodes',isAdmin?actions(button('手动添加',()=>nodeEditor(null)),button('添加节点',nodeSetup,'primary')):null);
  c.append(listing(['名称','地区','地址','通道',isAdmin?'心跳 / 安装状态':'状态',...(isAdmin?['最近外部探测']:[]),'活动连接','操作'],data,n=>{const state=element('span',undefined,'inline-status');state.append(badge(n.pending_install?'待安装':n.enabled?(n.online?(isAdmin?'心跳在线':'在线'):(isAdmin?'心跳中断':'离线')):'已停用',n.pending_install?'warm':n.enabled?(n.online?'good':'warm'):'neutral',n.pending_install?'clock':n.enabled?(n.online?'check':'clock'):'pause'));if(!isAdmin&&n.access?.allowed===false)state.append(element('small',n.access.reason||'当前套餐不包含此节点','install-error'));if(n.install_error)state.append(element('small',n.install_error,'install-error'));else if(n.pending_install)state.append(element('small',n.install_expires_at>Math.floor(Date.now()/1000)?'命令有效至 '+date(n.install_expires_at):'命令已过期，请重新复制','install-error'));state.querySelectorAll('small').forEach(s=>s.title=s.textContent);return[cell(n.name),n.region,cell(n.server_ip+':'+n.port,true),actions(badge('H2 · ECH','neutral','shield'),...(commerceEnabled?[badge(n.test_only?'测试节点':'正式节点',n.test_only?'warm':'neutral')]:[])),state,...(isAdmin?[nodeProbeStatus(n)]:[]),n.active,isAdmin?slotActions('96px 56px 56px'+(commerceEnabled?' 76px':''),
   n.pending_install?button('复制安装命令',()=>copyInstallCommand(n),'primary','key'):button('编辑',()=>nodeEditor(n)),
   n.pending_install||!n.enabled?button('删除',()=>deleteRecord('nodes',n),'danger'):null,
   n.pending_install?null:button(n.enabled?'停用':'启用',async()=>{await admin('nodes/'+id(n.id)+'/enabled',{enabled:!n.enabled});await render();}),
   ...(commerceEnabled?[button('调整范围',()=>nodeScope(n))]:[])
  ):slotActions('96px',n.enabled&&!n.pending_install&&n.access?.allowed!==false?button('下载配置 ZIP',async()=>download('tunnelX-node.zip',await api('nodes/'+id(n.id)+'/profile.zip',undefined,true))):null)];},current));if(isAdmin)c.append(helpNote('心跳表示节点进程最近上报；外部探测独立检查连接与证书。耗时是连接检查时间，不代表下载测速。'),helpNote('添加节点后，点击「复制安装命令」并在对应服务器用 root 执行即可接入。每次复制都会生成新命令并撤销上一次的安装凭据；待安装节点不会分发给用户。删除运行过的节点前，需停止服务并等待离线至少 90 秒。'));
 }
 if(current==='plans'){
  const c=section(root,'套餐与额度','管理使用周期、流量额度与账号设备限额。',data.length,'plans',isAdmin?button('新增套餐',()=>planEditor(null),'primary'):null);
  c.append(listing(['名称','周期','金额 / 币种','额度','设备数','限速','节点范围','状态','操作'],data,p=>[cell(p.name),p.kind==='traffic'?'当前有效周期':p.days+' 天',(p.price_cents/100).toFixed(2)+' '+(p.currency||'cny').toUpperCase(),p.traffic_bytes?bytes(p.traffic_bytes):'不限',p.kind==='traffic'?'沿当前套餐':p.devices,p.speed_limit?(p.speed_limit/125000).toFixed(1)+' Mbps':'不限',p.node_ids?.length?'指定 '+p.node_ids.length+' 个节点':'全部符合套餐类型的节点',badge(p.enabled?'启用':'停用',p.enabled?'good':'neutral',p.enabled?'check':'pause'),
   slotActions(isAdmin?'76px 56px 56px 56px':'76px',p.enabled?button('创建订单',async()=>{await api('orders',{plan_id:p.id});filters.orders='';view='orders';await render();}):null,...(isAdmin?[button('编辑',()=>planEditor(p)),!p.enabled?button('删除',()=>deleteRecord('plans',p),'danger'):null,button(p.enabled?'停用':'启用',async()=>{await admin('plans/'+id(p.id),{...p,enabled:!p.enabled});await render();})]:[]))
  ],current));c.append(helpNote(commerceEnabled?'套餐以订单创建时的金额和额度为准。测试模式不会实际扣款；正式付款由支付渠道通知确认。':'订单由管理员人工核实后开通。套餐修改不会改变已有订单；当前未接入在线收款。'));
 }
 if(current==='orders'){
  const names=new Map(users.map(u=>[u.id,u.email]));section(root,isAdmin?'订单工作空间':'我的订单','记录每一笔开通，处理每一项待办。',data.length,'orders').append(listing(['订单 ID',...(isAdmin?['用户']:[]),'套餐','金额 / 币种','状态','创建时间','操作'],data.slice().reverse(),o=>[
   cell(o.id,true),...(isAdmin?[cell(names.get(o.user_id)||o.user_id)]:[]),o.plan.name,(o.plan.price_cents/100).toFixed(2)+' '+(o.plan.currency||'cny').toUpperCase(),badge(({paid:'已开通',paid_review:'已付款待处理',pending:'待付款',cancelled:'已取消',expired:'已过期',refunded:'已退款'})[o.status]||o.status,({paid:'good',paid_review:'warm',pending:'warm',cancelled:'neutral',expired:'neutral',refunded:'neutral'})[o.status]||'neutral',({paid:'check',pending:'clock',cancelled:'close'})[o.status]),date(o.created_at),
   o.status==='pending'?slotActions('86px 76px',commerceEnabled&&o.user_id===me.id?button(o.test?'测试付款':'前往收银台',()=>checkout(o),'primary'):!commerceEnabled&&isAdmin?button('核实并开通',async()=>{await admin('orders/'+id(o.id)+'/fulfil',{});await render();},'primary'):null,button('取消订单',async()=>{await api((isAdmin?'admin/':'')+'orders/'+id(o.id)+'/cancel',{});await render();})):'—'
  ],current));
 }
 if(current==='audit')section(root,'管理操作记录','查看谁对哪个对象做了什么，以及保存前后的字段变化。时间统一显示为北京时间；历史简版日志保留原始动作码。',data.length,'audit').append(listing(['北京时间','操作者','操作摘要','对象','字段变更'],data.slice().reverse(),e=>[date(e.time),auditIdentity(e.actor_name,e.actor),auditOperation(e),auditIdentity(e.subject_name,e.subject),auditChanges(e)],current));
 if(current==='settings'){
  const c=card(root,'注册与试用','决定工作空间如何接纳新的使用者。','users'),settings=element('div',undefined,'settings-summary');for(const[label,value,tone]of [['公开注册',data.access.registration?'开启':'关闭',data.access.registration?'good':'neutral'],['试用时长',data.access.trial_hours?data.access.trial_hours+' 小时 / 1 GiB':'关闭',data.access.trial_hours?'accent':'neutral']]){const item=element('div',undefined,'setting-item');item.append(element('span',label),badge(value,tone));settings.append(item);}c.append(settings);
  c.append(button('编辑注册与试用',()=>{modal('注册与试用',[{name:'registration',label:'公开注册',type:'select',value:String(data.access.registration),options:[['true','开启'],['false','关闭']]},{name:'trial_hours',label:commerceEnabled?'试用小时数（商业模式固定关闭）':'试用小时数（0 表示关闭）',type:'number',value:commerceEnabled?0:data.access.trial_hours,min:0,max:168,step:1}],d=>admin('settings',{access:{registration:d.registration==='true',trial_hours:commerceEnabled?0:number(d.trial_hours,0,168)}}));if(commerceEnabled){$('fields').querySelector('[name=trial_hours]').disabled=true;$('dialog-description').textContent='商业模式通过获邀模拟购买授予测试权益，独立免费试用固定关闭。这里可调整公开注册开关。';}}));
  const news=card(root,'公告与更新','给使用者一条清晰的消息，一份明确的更新说明。','info'),release=element('div',undefined,'release-note');release.append(icon('download'),element('span','客户端发布版本'),badge(data.release.version,'neutral'));news.append(element('p',data.announcement||'暂时没有新公告。','announcement-text'),release);
  news.append(button('编辑公告与更新',()=>modal('公告与手动更新',[
   {name:'announcement',label:'公告',type:'textarea',value:data.announcement,required:false,maxlength:4000},{name:'version',label:'客户端版本',value:data.release.version||'v0.4.0',maxlength:64},
   {name:'url',label:'HTTPS 下载地址',type:'url',value:data.release.url,required:false,maxlength:2048},{name:'sha256',label:'文件 SHA256（64 位十六进制）',value:data.release.sha256,required:false,maxlength:64},
   {name:'notes',label:'更新说明',type:'textarea',value:data.release.notes,required:false,maxlength:4000}
  ],d=>admin('settings',{announcement:d.announcement,release:{version:d.version,url:d.url,sha256:d.sha256,notes:d.notes}}))));
  currentAnnouncement=data.announcement||'';markAnnouncementRead();
 }
 if(hasUnreadAnnouncement()&&current!=='overview'&&current!=='settings'){const banner=element('div',undefined,'notification-banner');banner.append(icon('info'),element('span','新公告：'+currentAnnouncement.slice(0,80)+(currentAnnouncement.length>80?'...':'')));banner.append(button('查看',async()=>{view=isAdmin?'settings':'overview';await render();},'text-button','arrow'));root.insertBefore(banner,root.firstChild);}
 if(!isAdmin&&$('content').dataset.page!==current)for(const child of root.children)child.classList.add('member-enter');$('content').dataset.page=current;$('content').replaceChildren(...root.childNodes);$('title').textContent=titles[current];$('breadcrumb').textContent=titles[current];$('page-description').textContent=descriptions[current];document.querySelectorAll('[data-view]').forEach(b=>{const selected=b.dataset.view===current;b.classList.toggle('selected',selected);if(selected)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});document.querySelectorAll('[data-view="settings"]').forEach(b=>b.classList.toggle('has-notification',hasUnreadAnnouncement()));
}
async function publicSettings(){try{const data=await api('public/settings');$('register').hidden=!data.registration;$('register').closest('.auth-register').hidden=!data.registration;}catch(e){message(e);}}
publicSettings();const initialIdentityReady=refreshIdentity().catch(e=>{if(me)message(e);});
setInterval(()=>{if(me&&view==='overview'&&!actionBusy&&!saving&&!$('dialog').open)render().catch(message);},30000);
let nodePoll=false;setInterval(async()=>{if(!me||view!=='nodes'||actionBusy||saving||$('dialog').open||nodePoll||document.activeElement?.matches('input'))return;nodePoll=true;try{await render();}catch(e){message(e);}finally{nodePoll=false;}},10000);
