// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateTrial() {
  return window['go']['main']['App']['ActivateTrial']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetLastNodeID() {
  return window['go']['main']['App']['GetLastNodeID']();
}

export function GetNodes() {
  return window['go']['main']['App']['GetNodes']();
}

export function GetSpeed() {
  return window['go']['main']['App']['GetSpeed']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetUser() {
  return window['go']['main']['App']['GetUser']();
}

export function GuestLogin() {
  return window['go']['main']['App']['GuestLogin']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function Register(arg1, arg2) {
  return window['go']['main']['App']['Register'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function TestLatency(arg1) {
  return window['go']['main']['App']['TestLatency'](arg1);
}
