// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateTrial() {
  return window['go']['main']['App']['ActivateTrial']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetNodes() {
  return window['go']['main']['App']['GetNodes']();
}

export function GetSpeed() {
  return window['go']['main']['App']['GetSpeed']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetUser() {
  return window['go']['main']['App']['GetUser']();
}

export function GuestLogin() {
  return window['go']['main']['App']['GuestLogin']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function Register(arg1, arg2) {
  return window['go']['main']['App']['Register'](arg1, arg2);
}

export function ResetSpeed() {
  return window['go']['main']['App']['ResetSpeed']();
}

export function TestLatency(arg1) {
  return window['go']['main']['App']['TestLatency'](arg1);
}
