// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateTrial() {
  return window['go']['main']['App']['ActivateTrial']();
}

export function BindEmail(arg1, arg2) {
  return window['go']['main']['App']['BindEmail'](arg1, arg2);
}

export function ChangePassword(arg1, arg2) {
  return window['go']['main']['App']['ChangePassword'](arg1, arg2);
}

export function CheckEmail(arg1) {
  return window['go']['main']['App']['CheckEmail'](arg1);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetAnnouncements() {
  return window['go']['main']['App']['GetAnnouncements']();
}

export function GetConnLog() {
  return window['go']['main']['App']['GetConnLog']();
}

export function GetDarkMode() {
  return window['go']['main']['App']['GetDarkMode']();
}

export function GetFavorites() {
  return window['go']['main']['App']['GetFavorites']();
}

export function GetKillSwitch() {
  return window['go']['main']['App']['GetKillSwitch']();
}

export function GetLastNodeID() {
  return window['go']['main']['App']['GetLastNodeID']();
}

export function GetNodes() {
  return window['go']['main']['App']['GetNodes']();
}

export function GetOrders() {
  return window['go']['main']['App']['GetOrders']();
}

export function GetProfile() {
  return window['go']['main']['App']['GetProfile']();
}

export function GetProxyMode() {
  return window['go']['main']['App']['GetProxyMode']();
}

export function GetSavedEmail() {
  return window['go']['main']['App']['GetSavedEmail']();
}

export function GetSpeed() {
  return window['go']['main']['App']['GetSpeed']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetUser() {
  return window['go']['main']['App']['GetUser']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GuestLogin() {
  return window['go']['main']['App']['GuestLogin']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function Register(arg1, arg2, arg3) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3);
}

export function SetDarkMode(arg1) {
  return window['go']['main']['App']['SetDarkMode'](arg1);
}

export function SetKillSwitch(arg1) {
  return window['go']['main']['App']['SetKillSwitch'](arg1);
}

export function SetProxyMode(arg1) {
  return window['go']['main']['App']['SetProxyMode'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function TestLatency(arg1) {
  return window['go']['main']['App']['TestLatency'](arg1);
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}
